"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../../styles/index.css'
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Final Next.js Website",
//   description: "Generated by create next app",
// };

import { ProductsProvider } from "../../context/ProductsProvider";
import { CartProvider } from "../../context/CartProvider";
import { ReactElement } from "react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      
      <body className={inter.className}>

    <ProductsProvider>
        <CartProvider>
        {children as ReactElement}
        </CartProvider>
    </ProductsProvider>
        </body>
    </html>
  );
}
