import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import Cart from "../../components/Cart";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Final Next.js Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
